### ISSUE TITLE
Images on Godot Asset lib page are broken

### ISSUE THREAD

**Issue by Goldenlion5648** [maji-git/multiplay-core#1]
The preview images on the asset lib page don't seem to work, did some files get moved?

https://godotengine.org/asset-library/asset/2889

**Comment by maji-git** [comment]
Thanks for opening this issue! There has been a file move and I've noticed this too. I've already submitted a new URL but doesn't seem to be working. I'll try again in the next release.

**Comment by maji-git** [comment]
Case Closed!
![image](https://github.com/maji-git/multiplay-core/assets/150906506/9d247bd4-ffb8-498c-b62e-1c5c110c1a0e)
