### ISSUE TITLE
Level Scene loads in editor tests, but doesn't load in exported projects

### ISSUE THREAD

**Issue by catprisbrey** [maji-git/multiplay-core#8]
**The Setup:**
A 3D project. A simple project, one characterbody3D controller with animation tree and a camera per player.
A basic greybox level, floor and walls with collisions, an environment and direction light node. Connecting using the EnetProtocol node. Debug UI turned on.

**The Issue:**
The editor works perfectly. Connections work great, players join and can interact. Works perfect. 

On exports of the same project (issue tested both for Windows and for Linux), the players load, but the level scene does not on client machines.

On the host machine, the player and level loads fine. When a peer connects to the session, The host machine's instance sees the new player appear, but they immediately fall through the floor. On the client machine's instance, their game didn't load the level scene. Only the players. They player instances into an empty world, and they see the host player there too, as they fall off the screen. So technically their position (falling through the floor, etc) is accurate.

This exact project and settings works perfectly in the editor for the host and client devices. The level loads perfectly, no issues. it's only once the project is exported that this behavior is observed.

We should test this in 2D as well, using the Demo project or something.

**Comment by maji-git** [comment]
What's the hosting environment you're having this issue on? It could potentially be a network loss(or high latency) issue.

And yep, will definitely do a stress test on this.

**Comment by catprisbrey** [comment]
Hosting from home, across the internet. But i doubt latency is the issue for the reason that

It works in the editor no problem. It's only when exported. As in, if i have a friend in New York, join my game in Arizona, both of us in Godot Editors, it connects and works great. If i export that project, and we both do play it again, only now will the level not load on the client side. We tested this several times, mixing linux with windows on the client side, and I tested again with another friend in Chicago. 

In the editor it always works, but when exported, the level scene doesn't appear, only the players.

**Comment by maji-git** [comment]
Issue confirmed. And the issue is not related to networking much, it's file name issue.

Godot adds `.remap` to the end of scene file name in release build.

Will be working on a fix soon

![Screenshot 2024-05-26 190414](https://github.com/maji-git/multiplay-core/assets/150906506/f144b788-a806-402e-b36f-1cad16a69c74)

**Comment by maji-git** [comment]
Issue Addressed https://github.com/maji-git/multiplay-core/pull/14
