### ISSUE TITLE
Bind Address not applying when not using the Debug_ui

### ISSUE THREAD

**Issue by catprisbrey** [maji-git/multiplay-core#9]
When not using the DebugUI, the bind address should be the address that is used for hosting the server, but testing didn't see to be the case. I also expected the connection to happen automatically without the Debug UI but it didn't load automatically. These were my changes to get it to run, but there's likely a better way to include the extra JSON info for certs etc rather than hardcoding around them.

![image](https://github.com/maji-git/multiplay-core/assets/43008564/7028a384-2796-4886-bce5-4ef235fff3f5)

Also worth testing if it's not just the bind address, but also the bind port is accurately updating in a non-debug. I haven't tested that currently. I suspect it's fine, but worth double checking.

**Comment by maji-git** [comment]
aight, missed this one. Yeah it used to be hard-coded... This pull request fixes it https://github.com/maji-git/multiplay-core/pull/11 

Also about additional auto start as join. I don't think it'll fit much because you can use the `online_join` function in production instead.
